---
kind: pipeline
type: docker
name: buildAmd64

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push
    - promote

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git
    settings:
      skip_verify: true

  - name: build
    image: noenv/maven
    pull: true
    environment:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    commands:
      - mvn -B clean package sonar:sonar
    when:
      event:
        - push

  - name: containerStaging
    image: noenv/maven
    pull: true
    environment:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    commands:
      - mvn -B clean package docker:build docker:push docker:remove -Ddocker.release.tag=${DRONE_DEPLOY_TO}-amd64
    when:
      event:
        - promote
      ref:
        - refs/heads/**

  - name: containerRelease
    image: noenv/maven
    pull: true
    environment:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    commands:
      - '[ -z "${DRONE_SEMVER_ERROR}" ] || exit 1'
      - mvn -B versions:set -DnewVersion=${DRONE_SEMVER}
      - mvn -B clean package docker:build docker:push docker:remove -Ddocker.release.tag=${DRONE_DEPLOY_TO}-amd64
    when:
      event:
        - promote
      ref:
        - refs/tags/*

---
kind: pipeline
type: docker
name: buildArm64

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push
    - promote

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git
    settings:
      skip_verify: true

  - name: build
    image: noenv/maven
    pull: true
    environment:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    commands:
      - mvn -B clean package
    when:
      event:
        - push

  - name: containerStaging
    image: noenv/maven
    pull: true
    environment:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    commands:
      - mvn -B clean package docker:build docker:push docker:remove -DskipTests -Ddocker.release.tag=${DRONE_DEPLOY_TO}-arm64
    when:
      event:
        - promote
      ref:
        - refs/heads/**

  - name: containerRelease
    image: noenv/maven
    pull: true
    environment:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    commands:
      - '[ -z "${DRONE_SEMVER_ERROR}" ] || exit 1'
      - mvn -B versions:set -DnewVersion=${DRONE_SEMVER}
      - mvn -B clean package docker:build docker:push docker:remove -DskipTests -Ddocker.release.tag=${DRONE_DEPLOY_TO}-arm64
    when:
      event:
        - promote
      ref:
        - refs/tags/*

---
kind: pipeline
type: docker
name: combineResults

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push
    - tag
    - promote

depends_on:
  - buildAmd64
  - buildArm64

clone:
  disable: true

steps:
  - name: stagingManifest
    image: quay.io/containers/buildah
    pull: true
    environment:
      NEXUS_TOKEN:
        from_secret: nexustoken
    commands:
      - buildah manifest create localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER}
      - "buildah manifest add --tls-verify=false --creds drone:$${NEXUS_TOKEN} localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER} nexus.noenv.com/noenv/${DRONE_REPO_NAME}:${DRONE_DEPLOY_TO}-amd64"
      - "buildah manifest add --tls-verify=false --creds drone:$${NEXUS_TOKEN} localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER} nexus.noenv.com/noenv/${DRONE_REPO_NAME}:${DRONE_DEPLOY_TO}-arm64"
      - "buildah manifest push --format v2s2 --tls-verify=false --creds drone:$${NEXUS_TOKEN} localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER} docker://nexus-upload.noenv.com/noenv/${DRONE_REPO_NAME}:latest"
      - "buildah manifest push --format v2s2 --tls-verify=false --creds drone:$${NEXUS_TOKEN} localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER} docker://nexus-upload.noenv.com/noenv/${DRONE_REPO_NAME}:${DRONE_DEPLOY_TO}"
      - buildah manifest rm localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER}
    when:
      event:
        - promote
      ref:
        - refs/heads/**

  - name: releaseManifest
    image: quay.io/containers/buildah
    environment:
      NEXUS_TOKEN:
        from_secret: nexustoken
    commands:
      - buildah manifest create localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER}
      - "buildah manifest add --tls-verify=false --creds drone:$${NEXUS_TOKEN} localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER} nexus.noenv.com/noenv/${DRONE_REPO_NAME}:${DRONE_DEPLOY_TO}-amd64"
      - "buildah manifest add --tls-verify=false --creds drone:$${NEXUS_TOKEN} localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER} nexus.noenv.com/noenv/${DRONE_REPO_NAME}:${DRONE_DEPLOY_TO}-arm64"
      - "buildah manifest push --format v2s2 --tls-verify=false --creds drone:$${NEXUS_TOKEN} localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER} docker://nexus-upload.noenv.com/noenv/${DRONE_REPO_NAME}:latest"
      - "buildah manifest push --format v2s2 --tls-verify=false --creds drone:$${NEXUS_TOKEN} localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER} docker://nexus-upload.noenv.com/noenv/${DRONE_REPO_NAME}:${DRONE_DEPLOY_TO}"
      - "buildah manifest push --format v2s2 --tls-verify=false --creds drone:$${NEXUS_TOKEN} localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER} docker://nexus-upload.noenv.com/noenv/${DRONE_REPO_NAME}:${DRONE_SEMVER}"
      - buildah manifest rm localhost/noenv/${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER}
    when:
      event:
        - promote
      ref:
        - refs/tags/*

  - name: notifyCoreship
    image: plugins/webhook
    settings:
      urls:
        from_secret: coreshiphook
      skip_verify: true
    when:
      status:
        - success
        - failure

  - name: notifyChat
    image: plugins/slack
    settings:
      webhook:
        from_secret: chathook
      channel: development
      username: ci
    when:
      status:
        - success
        - failure

---
kind: secret
name: chathook
get:
  path: ci/secrets
  name: chat_hook

---
kind: secret
name: coreshiphook
get:
  path: ci/secrets
  name: coreship_hook

---
kind: secret
name: nexustoken
get:
  path: ci/secrets
  name: nexus_token
